version: '3.8'
services:
  auth-service:
    build: .
    ports:
      - "3512:3512"
    env_file:
      - .env
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
